server:
  port: 8080

spring:
  application:
    name: book-my-show

  datasource:
    url: jdbc:h2:mem:bmsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO