version: '3.9'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

    restart: unless-stopped

    mem_limit: 300m

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD","bash","-c","echo ruok | nc localhost 2181"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

    networks:
      - backend-network

  redis:
    image: redis:7.2
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    restart: unless-stopped

    mem_limit: 150m

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

    networks:
      - backend-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin

    ports:
      - "9411:9411"

    restart: unless-stopped

    mem_limit: 256m

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - backend-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka

    depends_on:
      zookeeper:
        condition: service_healthy

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:

      KAFKA_BROKER_ID: 1

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # =====================================================
      # DUAL LISTENER ARCHITECTURE
      #
      # localhost:9092
      # Used by:
      # - VS Code
      # - Local Spring Boot Services
      #
      # kafka:29092
      # Used by:
      # - Docker Compose Services
      # - Platform Deployment
      # =====================================================

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    volumes:
      - kafka-data:/var/lib/kafka/data

    restart: unless-stopped

    mem_limit: 1g

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: ["CMD","kafka-topics","--bootstrap-server","localhost:9092","--list"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s

    networks:
      - backend-network

volumes:

  kafka-data:

  redis-data:

networks:

  backend-network:
    external: true