version: '3.9'

services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: Oracle123
      APP_USER: app_user
      APP_USER_PASSWORD: app_pass
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped
    mem_limit: 2g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD","bash","-c","echo 'SELECT 1 FROM dual;' | sqlplus -s system/Oracle123@FREEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - backend-network

volumes:
  oracle-data:

networks:
  backend-network:
    name: backend-network
    driver: bridge