spring:
  application:
    name: sb-05-proc-jdbcTamplate
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    username: user_db
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration