spring:
  application:
    name: template
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: app_user
    password: app_pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB