spring:
  application:
    name: template
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: app_user
    password: app_pass
    driver-class-name: oracle.jdbc.OracleDriver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    root: INFO
    com.vin: DEBUG